---
- hosts: localhost
  become: true
  tasks:
    - name: "add user"
      user:
        name: "raman"
        state: "present"
    - name: "install package"
      yum:
        name: httpd
        state: present
...
  