---
- hosts: localhost
  become: true
  tasks:
    - name: "add user"
      user:
        name: ankita
        state: "present"
    - name: "add user"
      user:
        name: test
        state: "present"
    - name: "add file"
      file:
        name: /tmp/ankita.txt
        state: "present"
...
  
