---
- hosts: localhost
  become: true
  tasks:
    - name: "add user"
      user:
        name: {{ item }}
        state: "present"
      loop:
        - ravi
        - jimi
    - name: "install package"
      yum:
        name: httpd
        state: present
...
  